package com.android.internal.graphics.palette;

import androidx.annotation.RequiresApi;

import java.util.List;

public interface Quantizer {
    /**
     * Create colors representative of the colors present in pixels.
     *
     * @param pixels    Set of ARGB representation of a color.
     * @param maxColors number of colors to generate
     */
    @RequiresApi(31)
    void quantize(int[] pixels, int maxColors);
    void quantize(final int[] pixels, final int maxColors, final Palette.Filter[] filters);
    /**
     * List of colors generated by previous call to quantize.
     */
    List<Palette.Swatch> getQuantizedColors();
}
